spring.application.name=quantity-measurement-app

spring.datasource.url=jdbc:h2:mem:quantitydb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=  932518293190-m60gv03el9v7kdiquq9h4ehdgtnnqjop.apps.googleusercontent.com
#${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=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
#${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# JWT
app.jwt.secret=myverysecurejwtsecretkeyforquantitymeasurementapplicationoauthjwtsecurity123456789
app.jwt.expiration=86400000

